### ISSUE TITLE
How to set python version?

### ISSUE THREAD

**Issue by karambaq** [seagle0128/doom-modeline#14]
How to set python version, in the line it says 2.7 but I use 3.6

**Comment by seagle0128** [comment]
Did you set `$PATH` for Emacs correctly`? Please check with `M-x get-env RET PATH` and⁄ `C-M ! python --version RET`.

**Comment by karambaq** [comment]
@seagle0128 
<img width="1212" alt="2018-08-03 18 42 40" src="https://user-images.githubusercontent.com/14233969/43652144-07a7c148-974d-11e8-9a19-ac7cdf57164d.png">
python version says it 2.7.15

**Comment by seagle0128** [comment]
I believe Python 2.7 is used in your emacs env. Would you please provide the output of `M-S ! python --version RET`?

**Comment by karambaq** [comment]
Yes, it says 2.7.15

**Comment by karambaq** [comment]
unfortunately, can't make it work :(

**Comment by r0m4n27** [comment]
I think it's happening, because in line 1154 it searches directy for the "python" executeable. So you would have to change it there directly to "python3".

**Comment by karambaq** [comment]
@r0m4n27 I set it like that:

    (setq python-shell-interpreter "/usr/local/bin/python3"
          flycheck-python-pycompile-executable "/usr/local/bin/python3"
          python-shell-exec-path "/usr/local/bin/python3")

But modeline still showing 2.7.15 version :(

**Comment by seagle0128** [comment]
@karambaq I think you didn't get the point. The `doom-modeline` use `python --version` to get the version. If `python` is not in the $PATH of Emacs (not in shell), the version is not what you want. Per your description, both `python` and `python3` are in your system. The simple way is make a link symbol for `python3`, and put it into `/usr/local/bin`. I don't use `python-shell-interpreter` since people may use `ipython` or something else.

**Comment by seagle0128** [comment]
I'd like close it now since there is no more feedback. Please feel free to reopen if you still have any issue.

**Comment by bebound** [comment]
Thanks to #18 , `  (setq doom-modeline-python-executable "python3")` should works.
However, on my Mac, it changes `Python 2.7.10` to `Python`, the version disappears...

**Comment by seagle0128** [comment]
@bebound I guess Python2 is not in `exec-path`. Eval `(executable-find doom-modeline-python-executable)` in Emacs and check the output, please.

**Comment by bebound** [comment]
If I set the variable to `python3`, it outputs `/usr/local/bin/python3`. Otherwise, it outputs `/usr/bin/python`.

I'm using macOS and Spacemacs, `2.7.10` is the System Python, and I used homebrew to install `2.7.15` and `3.7.0`. It seems that the `$PATH` in Emacs GUI is weird.


In shell, the `$PATH` is `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:.:/Users/kk/.gem/ruby/2.3.0/bin/`
In emacs, `M-x` shell, `$PATH` is `/usr/bin:/bin:/usr/sbin:/sbin:.:/Users/kk/.gem/ruby/2.3.0/bin/:.:/Users/kk/.gem/ruby/2.3.0/bin/`, I don't know what prepend `/usr/bin` at the beginning.

**Comment by seagle0128** [comment]
You should set correct environment variables in Emacs. You can use `exec-path-from-shell` to import env vars from shell.

**Comment by bebound** [comment]
OK, I'll try this.
But after I set python-executable to python3, the version number disappears, is this correct? `/usr/local/bin/python3` is python `3.7.0`

**Comment by seagle0128** [comment]
@bebound I think you don't get the point. after `(setq doom-modeline-python-executable "python3")`, you still need to confirm if `python3` is in `exec-path` and `$PATH` in emacs. Or you just use `(setq doom-modeline-python-executable "/usr/local/bin/python3")`.

**Comment by bebound** [comment]
Ahh, I see, thank you.

**Comment by CruiseDevice** [comment]
I am using this in my init.el

```
(when (and (executable-find "python3")
             (string= python-shell-interpreter "python"))
    (setq python-shell-interpreter "python3"))

  ;; Env vars
  (with-eval-after-load 'exec-path-from-shell
    (exec-path-from-shell-copy-env "PYTHONPATH"))
```
