### ISSUE TITLE
Add a HUD

### ISSUE THREAD

**Issue by jwintz** [seagle0128/doom-modeline#143]
A HUD in terms of modeline is a graphical representation of the position in the current buffer.

**Alternatives**
- `spaceline` implements it, quite nicely.

**Proposition**
- The segment may be forked from there ...

**Comment by seagle0128** [comment]
Thanks for the reporting!

After the investigation, I don't think it's a good idea to add a HUD in `doom-modeline`. There are three reasons.

1. It breaks the minimalism design styleb.
1. The position segment and  nyan segment should indicate the position clearly.
1. The HUB will bring negative impacts to the performance. 

So I am not going to implement this feature. If you and/or others have solid justifications to convince me, I am fine to reconsidering the solution. Thanks!

**Comment by marienz** [comment]
I've implemented this (see https://github.com/marienz/doom-modeline/commit/5d476de7019999ec0c94061c7474f28bb847431a) and was wondering if you'd consider having it in doom-modeline.

* On minimalism: I've put this at the start of my modeline as a replacement of the "bar" segment, and disabled `doom-modeline-percent-position` and `size-indication-mode`. It gives me a rough indication of where in the buffer I am and how large the buffer is (I rarely care about the actual size as displayed by `size-indication-mode`, but I like to know "is this buffer a few dozen lines or thousands of lines"). So replacing the bar with a hud let me remove a bunch of numbers from my modeline. (I was hoping to put it at the end, against the right window border, but I haven't figured out how to align it correctly...)
* On alternatives: I looked at nyan but it takes up a lot more space. The "hud" is only a few pixels wide. And graphical indicators are easier for me to read at a glance than numeric ones.
* On performance:
  * I'm caching the hud image as a window property, generating a new one if the image size or indicator position changes. That means we only generate a new image when scrolling or selecting a different buffer (both of which I expect to already be slow because they have to redraw the screen). Checking if the cache is valid should be cheap (`(window-start)`, `(window-end)` and `(buffer-size)` return cached values), and reusing the cached image is otherwise exactly like the "bar" segment.
  * If we miss the cache, redrawing the image is still decently fast: I tested replacing the `(window-start)` and `(window-end)` calls with calls to `random` to force a different image each time the modeline redraws, and still got acceptable performance on the slowest device I have available for testing graphical Emacs (an ARM-based Chromebook). This could do with more testing, but I'm counting on the cache keeping redraws under control.

Please let me know what you think!

**Comment by seagle0128** [comment]
Aha, interesting! 
@marienz , thanks for letting me know it. May I see the screenshots?
I took a quick look at the codes, and it seems good. It's clean and fast as you described above. Would you please make a PR? I can reopen this issue and close it by your PR.

**Comment by marienz** [comment]
Glad you like it!

Doom's default theme, large file:
![image](https://user-images.githubusercontent.com/516706/118251721-430a6100-b4eb-11eb-9d74-6c6a77c4321d.png)

Different theme, smaller file: 
![image](https://user-images.githubusercontent.com/516706/118252317-f83d1900-b4eb-11eb-938a-643eddd6bfec.png)

PR: #439.
