### ISSUE TITLE
Modeline covers Helm (I think?)

### ISSUE THREAD

**Issue by BrandonShega** [seagle0128/doom-modeline#153]
**Describe**
I'm new to spacemacs (few months of use) and I'm using Doom modeline and one thing I noticed sometimes is when I press `SPC` the modeline covers the window with all of the commands or it doesn't move it up, one of the two.

**Steps and Expected**
1. Open Spacemacs
2. Press `SPC`

**Environment:**
 - OS: macOS Mojave
 - Version 10.14.1
 - Package version I'm not sure how to find this

**Additional context**
![modeline](https://i.imgur.com/W2Auy0D.png)

**Comment by BrandonShega** [comment]
Looks like maybe this is related to `which-key`?

**Comment by seagle0128** [comment]
It's which-key window. I didn't get your point. What's the problem you encounter?

**Comment by BrandonShega** [comment]
The problem is the modeline is covering the bottom row of keys and I'm not sure why.  This only happens with doom modeline.  I temporarily fixed it by moving the which-key window to the right instead of the bottom.  I was mostly wondering if it was a setting I had incorrectly that causes that.

**Comment by seagle0128** [comment]
Apparently it's not an issue of `doom-modeline`, while it's a configuration issue. It doesn't exist in vanilla Emacs and my configurations.  You may need to check `which-key-popup-type` and the related configurations in `spacemacs`. I am not using spacemacs so I am unable to specify the root cause. Sorry!

![image](https://user-images.githubusercontent.com/140797/55632955-f7eed180-57ed-11e9-8742-2c668e94022c.png)

**Comment by thornjad** [comment]
This is a bug in Spacemacs, but looks like the fix might not be in the develop branch yet: syl20bnr/spacemacs#11165. Looks like @BrandonShega already found it.

**Comment by seagle0128** [comment]
Thanks for the information, @thornjad !
