### ISSUE TITLE
Always show right aligned info even if the file path is really long

### ISSUE THREAD

**Issue by bsekura** [seagle0128/doom-modeline#179]
Great modeline!

I would love to be able to force things aligned to the right (branch name, etc) to always be visible even if the file path gets really long. Or, in other words, cut the file path to selected size to prevent stuff on the right to shift beyond visible area.

Thanks

**Comment by seagle0128** [comment]
Honestly I have no idea how to implement it without performance impacts. To calculate the mode-line width dynamically, the performance will be impacted significantly.

**Comment by bsekura** [comment]
Unfortunately I know next to nothing about emacs mode line. 
Tmux, for example, has set -g status-left <stuff> and set -g status-right <stuff>, which makes me think that if mode line can drawn and calculated from both ends and meet in the middle, that could be one of the solutions, That is, if emacs mode line even allow this sort of thing.

https://github.com/vim-airline/vim-airline
https://github.com/edkolev/tmuxline.vim

These projects take the approach of having preset stuff at both left and right aligned ends that do not move when window is resized.

**Comment by tshu-w** [comment]
@seagle0128 Is it possible to use filename style unless detect project.

**Comment by seagle0128** [comment]
@tshu-w  A new style `auto` is introduced.

```elisp
Given ~/Projects/FOSS/emacs/lisp/comint.el
  auto => emacs/lisp/comint.el (in a project) or comint.el
  truncate-upto-project => ~/P/F/emacs/lisp/comint.el
  truncate-from-project => ~/Projects/FOSS/emacs/l/comint.el
  truncate-with-project => emacs/l/comint.el
  truncate-except-project => ~/P/F/emacs/l/comint.el
  truncate-upto-root => ~/P/F/e/lisp/comint.el
  truncate-all => ~/P/F/e/l/comint.el
  relative-from-project => emacs/lisp/comint.el
  relative-to-project => lisp/comint.el
  file-name => comint.el
  buffer-name => comint.el<2> (uniquify buffer name)"
```

**Comment by x-ji** [comment]
I don't think `auto` actually fixes the problem though... If I'm in a project, the full path of the file in the project will always be displayed, right? Then if I divide the window to have multiple buffers, the right side of the modeline will still not be shown.

Some other modeline packages e.g. https://github.com/TheBB/spaceline solve this by defining the left-side components and the right-side components of a modeline separately.

For now the best way I can find to solve this problem is to just set the style to ones like `truncate-all` or `file-name`, which are the shortest options available.

**Comment by x-ji** [comment]
Or I wonder if it is possible to set a hard limit on file name length, and simply truncate the left part of the string when the limit is surpassed.

**Comment by seagle0128** [comment]
@x-ji As you said, `truancate-all` and `file-name` styles work for you. Moreover, you can define your own modeline with `doom-modeline-def-modeline`. It's flexible.

If you think you  have good ideas, please submit PRs or raise a feature request with more details.

**Comment by seagle0128** [comment]
I got a new idea. 

Introduce a new option `doom-modeline-width-limit` (e.g. default value is `fill-column` + 20). If the window width <= limit , only displaying the buffer name , otherwise display as the `doom-modeline-buffer-file-names-style`. 

Meanwhile,  add some optional segments, which are displayed while the window width > limit. e.g. battery minor-modes input-methods...

Any thoughts?

**Comment by seagle0128** [comment]
The patch a25dc7267eccb3138793fe71b598d337d2447ae0 is  committed.

**Comment by x-ji** [comment]
Thanks, this seems to have worked exactly as described 👍
