### ISSUE TITLE
How to keep on global modeline with buffers are split

### ISSUE THREAD

**Issue by benmezger** [seagle0128/doom-modeline#194]
This is not necessarily an issue with Doom's modeline, but I wonder if there is any way I can have one global modeline only, and not have "duplicate" modelines when buffers are split.

I've seen this is [possible](https://emacs.stackexchange.com/a/9577) with Powerline, I wonder if Doom has something similar.

**Comment by seagle0128** [comment]
According to the solution 1, please try

```elisp
;; wrap your mode-line-format
((:eval (when (doom-modeline--active) ...)))
(set-face-attribute 'mode-line-inactive nil
                    :underline t
                    :background (face-background 'default))
```

**Comment by benmezger** [comment]
Thanks @seagle0128. That did the work.

**Comment by lyndhurst** [comment]
I am very sorry to re-open such an old issue, but I am trying to achieve the same goal and did not think I should open a new one. @seagle0128 , please let me know if I am wrong.

I have tried maple-line, but options are not explaned at all, and all I managed to do was to have a unique modeline at the bottom that completely hides doom-modeline.

For solution 1, I am configuring my first doom-emacs install, I am a very recent neovim convert and I do not understand how to use that code. From what I can make of it, the wrapping would occur in the doom-emacs configs rather than in my private config files which I'd rather not do so early in the learning process.

@benmezger I would be very grateful if you could elaborate on what worked for you and if this solution would not interfere with the doom pre-installed  themes and configs.

Thanks for your time.
