### ISSUE TITLE
Modeline overflows window

### ISSUE THREAD

**Issue by juliandemille** [seagle0128/doom-modeline#211]
**Describe the issue**
The modeline has data that goes past the edge of the window, shown here:
![2019-08-18-133210_1920x1080_scrot](https://user-images.githubusercontent.com/8127111/63228099-9c314d80-c1bc-11e9-8bb5-d3209444962c.png)

**Steps to reproduce**
Unknown, this has always been an issue for me.

**Environment:**
OS: Manjaro Linux
Version: b47fe7b65ad164581b5aef88e3efa20b93178da6

**Comment by seagle0128** [comment]
- What's the icon before the number 1?
- What's the font are you using?

**Comment by juliandemille** [comment]
I'm not sure what that icon is, but I'm pretty sure `lsp-mode` is putting it there and that it's from `all-the-icons.el`

**Comment by seagle0128** [comment]
No, it's not. LSP icon is `rocket`. I guess it's github, email or irc. Apparently, the icon is incorrect. The font configurations is wrong IMO. Some fonts (icons) seem being overridden.

**Comment by juliandemille** [comment]
@seagle0128 It's Flycheck from `doom-emacs`, sorry for the configuration. Can you elaborate on fonts being overridden?

**Comment by seagle0128** [comment]
@juliandemille I think the last icon is for `flycheck`, right? I am confirming what's this icon: 
<img width="61" alt="Screen Shot 2019-08-22 at 4 30 15 PM" src="https://user-images.githubusercontent.com/140797/63499346-43362200-c4fa-11e9-853e-1456325474d0.png">

The icon is 2 char-width, so that caused this issue. But I cannot find this icon is `doom-modeline`. That's why I suspecting there were font mis-configurations in your env. Can you make sure which package or mode it belongs to?

I have some workarounds or solutions here.
1. Confirm and fix the font issue.
1. Add this icon to `doom-modeline-rhs-icons-alist`, and eval `(doom-moddeline--set-font-widths doom-modeline-rhs-icons-alist)`.
1. Define your main mode-line with `doom-def-modeline`, and add extra spaces at the last. Refer to 5 of [FAQ](https://github.com/seagle0128/doom-modeline#faq)

**Comment by juliandemille** [comment]
This icon is coming from flycheck. The icon is in doom-modeline at `doom-modeline-segments.el:674`

**Comment by seagle0128** [comment]
@juliandemille I'm not talking about the last icon in the mode-line,  while talking about the yellow dot before the number "1".

**Comment by seagle0128** [comment]
Put your mouse on the icon. What do you see?

**Comment by juliandemille** [comment]
I think `doom-emacs` disabled popup text, but I tried right clicking it and got this:
![2019-08-23-105159_474x22_scrot](https://user-images.githubusercontent.com/8127111/63601757-0d457c00-c594-11e9-930c-e6f2a8797904.png)

**Comment by seagle0128** [comment]
`(setq mode-line-default-help-echo #'mode-line-default-help-echo)` to enable the tip.

**Comment by juliandemille** [comment]
I think `doom-emacs` is disabling tips on hover elsewhere. It still isn't showing up.

**Comment by seagle0128** [comment]
And `(setq show-help-function 'tooltip-show-help)`.

**Comment by juliandemille** [comment]
Okay, now I get tooltips for other segments, but not the unknown segment.

**Comment by seagle0128** [comment]
That's why I don't like `spacemacs` or `doom-emacs`, which change vanilla Emacs a lot. Okay, then you can try the solutions above, and close it if you are fine.

**Comment by juliandemille** [comment]
The space solution worked.

**Comment by MassimoLauria** [comment]
Sorry to show up in a closed issue, but I had a similar problem.

My modeline with icons overflowed, too.
In the end it turned out that the culprit was a custom function I wrote that I use to abbreviate the major modes, since `diminish` does not work on Major modes. (e.g. Python --> Py ).

**Comment by seagle0128** [comment]
@MassimoLauria I guess I got the root cause. `doom-modeline` calculates the length by mode-line-format. If the major modes are abbreviated by trick, the calculation will be inaccurate. That's why all work well after disabling it.
