### ISSUE TITLE
modeline eats last set of tags when using org-fast-tag-selection

### ISSUE THREAD

**Issue by joefromct** [seagle0128/doom-modeline#291]
**Describe**
`doom-modeline` eats last set of tags when using `org-fast-tag-selection` (via `org-set-tags-command`).

Below is a screenshot with `emacs -Q` and below that is my usual doom config (with modeline).

In the two screenshots below you can see (circled in red) `emacs -Q` shows my tags for selection, doom is missing the bottom line of tags.  

I think the org code generating the overlay is [here](https://github.com/bzg/org-mode/blob/master/lisp/org.el#L12560).

I have tried with tool-bar-mode on/off, menu-bar-mode on/off. 

Disabling the `:ui modeline` in the doom `init.el` is the only thing that seems to make the tags visible. 

Also, note that _sometimes_ on doom startup, the first time i look at the tags it seems to work.  Every subsequent call hides the bottom of the tags line. 

**Steps and Expected**
Create a simple org-file, and call `org-set-tags-command` (`C-c C-g`). 

**Environment:**
 - OS: MacOS
 - Version Catalina
 - Package version:  Doom v2.0.9

**Additional context**
`emacs -Q` : 
![emacs](https://user-images.githubusercontent.com/3342707/72934691-b4883400-3d29-11ea-9836-02294b9bea52.png)

Doom somewhat standard config:

![doom](https://user-images.githubusercontent.com/3342707/72934701-b9e57e80-3d29-11ea-9d4f-47bc89ba128c.png)

**Comment by joefromct** [comment]
Henrik explained the following in discord:

> @joefromct by default, doom hides the modeline in the tags popup. Have you disabled :ui popup?

Adding `(popup +default +all)` back into my config corrected my issue.  

Thanks,

**Comment by condy0919** [comment]
What's the root cause behind the issue? Looks like the modeline is too tall

**Comment by borysn** [comment]
hi,

am experiencing this issue in the latest version of doom-modeline from melpa, version 20220309.239. using emacs 27.2 on AlpineLinux. here is my related [stack exchange post](https://emacs.stackexchange.com/questions/70852/org-agenda-tag-selection-buffer-is-too-small-to-view-any-tags/70856#70856)

here is a screenshot showing org-fast-tag-selection buffer not displaying correctly due to doom-modeline
![org-fast-tag-selection buf](https://i.stack.imgur.com/uqsME.png)

disabling doom-modeline corrects the `org-fast-tag-selection` buffer display

the bug can be mitigated with customizing doom-modeline height, but doom-modeline's height can only go so small and the view still does not display properly 

``` elisp
(custom-set-variables
  `(doom-modeline-height 15))
```

a better temporary work around has been to re-bind `C-c C-q` from `org-mode-map` to a lambda that disables doom-modeline before operations, and re-enables doom-modeline after operations. this works better imo, but i am unable to figure out why doom-modeline-mode is not re-enabled if the fast-set-tags buffer is quit with `q` (tried following the source code, no errors raised, nothing thrown [org.el, etags.el, window.el])

``` lisp
(define-key org-mode-map (kbd "C-c C-q")
  (lambda (&optional arg)
    (interactive "P")
    (doom-modeline-mode -1)
    (org-set-tags-command arg)
    (doom-modeline-mode 1)))
```

saw issues [#480] and [#485] but do not see a solution ever presented

**Comment by seagle0128** [comment]
@borysn It does work well in my laptop. Check whether this workaround work for you.

```elisp
(advice-add #'fit-window-to-buffer :before (lambda () (redisplay t)))
```

Actually it's an issue of Emacs itself, and has been fixed in 29. However, an workaround was provided in `doom-modeline-mode`. Please refer to `doom-modeline-redisplay`. I suggest to test with `emacs -Q`.

**Comment by borysn** [comment]
@seagle0128 nice! the advice-add is a better workaround, works fine with `C-c C-c` action too. just need `&rest r` arg in the lambda. 

saw the notes on a problem in emacs and a fix for later versions of emacs, but i thought that was related to the flickering issue which was mentioned in the same bug reports, so i was left confused when i still ran into the bug but the bugs were closed. 

thank you for the response! love doom-modeline :)

**Comment by seagle0128** [comment]
@borysn Correct. I've updated the snippet above. But I have to say the workaround will bring some negative performance issue. 

I'm confusing why `doom-modeline-redisplay` is not working for you. Can you please check this function in your env?

**Comment by borysn** [comment]
@seagle0128 i can see the function docs using `C-h f`, so it's there
