### ISSUE TITLE
void-variable when

### ISSUE THREAD

**Issue by kurnevsky** [seagle0128/doom-modeline#293]
Doom modeline started producing error `(eval (doom-modeline-segment--modals)) signaled (void-variable when)` after each user action.

**Environment:**
 - OS: Arch Linux
 - Package version 20200202.537

**Comment by duianto** [comment]
Confirmed.
It doesn't happen with a previous version: `doom-modeline-20200124.1510`

System Info:
- doom-modeline-20200202.537
- GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29

**Comment by seagle0128** [comment]
There is no code change except comments or docs since 2020-1-24.
Who can provide the details to reproduce this issue?

**Comment by duianto** [comment]
The error message appears in the messages buffer when a lot of different keys are pressed.

It doesn't always repeat when the cursor is just moved horizontally (`C-f` or `C-b`), or vertically (`C-n` or `C-p`), but it repeats if one alternates horizontally and vertically.

It also repeats:
- when recentering `C-l` (l = lowercase L) the cursor between each vertical movement.
- if a message is printed in the messages buffer, for example by just pressing `C-g` or when the cursor is moved up from the first or down from the last line.
- when jumping to the beginning `M-<` or end `M->` of the buffer.
- when selecting another application and back to Emacs with `Alt-Tab`, probably because the modeline loses and gains focus.
- etc.

**Comment by seagle0128** [comment]
Which  modal modes are enabled? e.g. evil, god?

**Comment by duianto** [comment]
`doom-modeline` is the only installed package.

**Comment by seagle0128** [comment]
Thanks, all. Please test the latest version.

**Comment by duianto** [comment]
Confirmed.

After removing the stray period after the `doom-modeline--overwrite` docstring
and deleting `doom-modeline-segments.elc`
Now there are no error messages.

Thanks 👍
