### ISSUE TITLE
Insert mode indicator goes funny in org-mode

### ISSUE THREAD

**Issue by tecosaur** [seagle0128/doom-modeline#300]
**Describe**
For some reason, now, whenever I'm in org-mode the "Insert mode" icon messes up.

This happens after adding `(add-hook! 'org-mode-hook #'+org-pretty-mode #'mixed-pitch-mode)` to my config.

Fixed by `(custom-set-faces! '(doom-modeline-evil-insert-state :weight bold :foreground "#339CDB"))`

**Steps and Expected**
1. Use doom emacs
2. Add `(add-hook! 'org-mode-hook #'+org-pretty-mode #'mixed-pitch-mode)` to config
3. Hope there isn't a combination of other settings I've missed
4. Open buffer in org-mode, switch to insert
5. Expect a blue dot, see a blue `T`

**Environment:**
 - OS: Linux (distro: solus)
 - Version 5.4.12-144.current
 - Package version 31a5ae99b8667ff8b6f59664f792283d1adc6765

**Additional context**
![image](https://user-images.githubusercontent.com/20903656/74093652-cf232100-4b0f-11ea-8076-48783e11994d.png)

There may be some interaction with other config settings going on. My full config can be found at https://github.com/tecosaur/emacs-config

According to Henrik
> Looks like an issue with cascading faces, and the all-the-icons faces loses out. Should probably be reported upstream.

**Comment by seagle0128** [comment]
I think it's an compatibility issue of `doom-emacs`, which uses other unicode fonts  (e.g. Fira). I know there were a several similar issues  before.

**Comment by seagle0128** [comment]
@tecosaur Try the latest version. If the issue still exists, please file an issue for `doom-emacs`.

**Comment by karetsu** [comment]
I am also experiencing this issue although my steps to recreate are slightly different and I am seeing a unicode Z rather than a T:

1. Use doom emacs
2. Enable `mixed-pitch-mode`
3. Enter insert mode
4. Observe a symbol which is not the expected circle (which does appear in every other mode)
5. Disable `mixed-pitch-mode`
6. Enter insert mode
7. See the circle as expected

I have tried the latest version as you suggested to @tecosaur and the issue persists. This is here for posterity in case the issue comes back to being a `doom-modeline` rather than a `doom` one.

My config is [here](https://github.com/karetsu/doom-overlay) if needed.

**Comment by seagle0128** [comment]
@karetsu I believe it's an issue of `doom`. See https://github.com/hlissner/doom-emacs/commit/909c27796843a4b3e236354f96d0dd98266e5b97.

**Comment by tecosaur** [comment]
Hmm. That commit only seems to affect `+fira` or `+isoveka`. I'm not sure about
@karetsu but I know that I have neither of those options enabled.

**Comment by seagle0128** [comment]
@tecosaur I didn't say that commit addressed your issue. I just mean the root cause is the font configurations of `doom` breaks the `all-the-icons`. The solution should be similar.

BTW, I can confirm vanilla Emacs has no such issue.

**Comment by tecosaur** [comment]
Ok. Thanks for following up, I'll pass this on to Doom Emacs.
