### ISSUE TITLE
doom-modeline doesn't reset state when dap debug is terminated

### ISSUE THREAD

**Issue by thermopyle** [seagle0128/doom-modeline#327]
**Describe**
When a dap debugging session is started using dap-debug, doom-modeline changes its background color. With my theme (doom-vibrant) the entire modeline turns into an orange-like color. An icon is also visible on the modeline, kind of like a little bug.
When the debugging session is terminated using dap-disconnect or the dap-hydras 'Q' and 'q' doom-modeline does not return to its original state, the background color is still this vibrant orange-like color and the debug icon is still visible.

**Steps and Expected**
Start a dap debug session using dap-debug.
Stop the debug session using dap-disconnect.

**Environment:**
 - OS and version: MacOS 10.14.6 Mojave.
 - Emacs Version: 27.0.60.
 - Configuration: vanilla Emacs built from source.
 - Package version: 20200322.636

**Comment by seagle0128** [comment]
I couldn't reproduce it, with GNU Emacs 28.0.50 on macOS 10.15. I was using `lsp-python-ms` and `dap-mode` to debug the python files.

**Comment by ericdallo** [comment]
I found the bug @seagle0128, the problem is that if the user starts the debug session in buffer A, we update to the orange color and if we terminate the session, we update back to the original color. The problem is when we start on buffer A and terminate in buffer B, then the color wont go back to the original.
1. [this](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1963) is buffer local, so [here](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1972) it will be `nil`
2. I don't know for sure, but we update the doom-modeline only on the buffer that started the debug? and when we change to a buffer B (a breakpoint, for example) the modeling is not orange.

We may need a way to set a variable for all buffers of that session or something like that, what do you think?

**Comment by seagle0128** [comment]
It makes sense. It's a bug.
