### ISSUE TITLE
Feature request: be able to show a list minor modes

### ISSUE THREAD

**Issue by Havner** [seagle0128/doom-modeline#59]
As in the topic, same list that the default modeline or spaceline shows. The one that can be modified with packages like delight.

**Comment by seagle0128** [comment]
I don't like displaying minor modes personally. The mode-line looks too long and complicated.
Since someone like it, I implement a simple segment but disable it by default.

**Comment by seagle0128** [comment]
`(setq  doom-modeline-minor-modes t)` to enable.

**Comment by Havner** [comment]
Thanks!

Works almost great :-)

I've found you disable projectile-dynamic-mode-line in doom modeline. What for? It shouldn't make any difference when minor modes are not visible, but it does make a difference when they are shown.

**Comment by Havner** [comment]
Also if possible would you be so kind to create a customizable face for it? The same way one exists e.g. for major mode (doom-modeline-buffer-major-mode).

**Comment by seagle0128** [comment]
> You commented that it disables "projectile mode-line segment". I don't think that's a segment, it's just a lighter.

You are right! It's a lighter. Because all minor-modes are disabled in `doom-modeline` before, I disabled it as well, but not necessary now. I will remove it.

> also mouse clicks are completely broken.

I am investigating this minor issue.

> if possible would you be so kind to create a customizable face for it? 

Since they are minor modes, I just keep them as default face, which keeps mode-line clean and simple. I don't want to make too many colors from `doom-themes`. Do you have any idea for the minor modes?

**Comment by Havner** [comment]
> Since they are minor modes, I just keep them as default face, which keeps mode-line clean and simple. I don't want to make too many colors from `doom-themes`. Do you have any idea for the minor modes?

You can create the face and make it inherit from the default face and not touch doom-themes at all, I don't mind. But this way I'll be able to customize it myself.

**Comment by seagle0128** [comment]
@Havner Okay. I know what you mean exactly. Will drop in soon.

**Comment by Havner** [comment]
Cheers!

Works great now.

**Comment by Havner** [comment]
One question though, partly related. Today I've noticed that LSP has it's own segment, or something generic, that's showing LSP. Together with minor mode segment I see it twice. This is not a bug in minor mode segment but I'd like to know how to identify the other one displaying it.

![doom-modeline](https://user-images.githubusercontent.com/6246347/49581807-6b252b80-f953-11e8-90df-0cd3a7ea4ee4.png)

**Comment by seagle0128** [comment]
`lsp-mode` provides the lighter in the minor mode. `lsp` segment leverage the same lighter because of the compatibility with two different co-existing interfaces (`lsp-mode.el` and `lsp.el`). I discussed with the maintainers of `lsp-mode`. We will continue improving it with the new APIs after the legacy codes are deleted. I think you can just remove `lsp` lighter from the minor modes segment.

Well, today I don't provide all enablers for each segment. Only for `minor-modes`. I may add others but no promise for all segments.

**Comment by Havner** [comment]
> I think you can just remove `lsp` lighter from the minor modes segment.

There doesn't seem to be any provided means to do this. It was easier to disable doom line segment for me.

**Comment by seagle0128** [comment]
`diminish` or `delight` is easy to remove lighters on mode-line. Or just redefine `lsp-mode-line`. It's up to you, anyway. Cheers!

**Comment by Havner** [comment]
I use delight, but LSP mode line is dynamic. Delight won't help here. And there is no lsp-mode-line variable defined in newest LSP.

**Comment by seagle0128** [comment]
Seems `diminish` does work. Redefining `lsp-mode-line` function or overriding it with `ignore` also does work...
