### ISSUE TITLE
Modeline doesn't show git info

### ISSUE THREAD

**Issue by valignatev** [seagle0128/doom-modeline#60]
Hi, thanks for providing this nice package outside of doom-emacs! I was able to install and run it successfully, but for some reason I don't see git integration which is present in screenshots. This, for example, is what's on my modeline with default configuration:
![image](https://user-images.githubusercontent.com/7038954/49473612-901a8100-f823-11e8-8bb2-e81fdfe22fc3.png)
Just in case, my doom-modeline code:
```emacs-lisp
  (use-package doom-modeline
    :ensure t
    :defer t
    :hook (after-init . doom-modeline-init))
```

What am I missing?

**Comment by valignatev** [comment]
Looks like this: https://github.com/seagle0128/doom-modeline/blob/dbfdf1b0b06ddda3d365ac1d53f271fc62775a9b/doom-modeline.el#L904

returns `nil` for me although the file is certainly under git.

**Comment by seagle0128** [comment]
Hello, `doom-modeline` depends on `vc-mode` to detect vcs info. I believe `doom-emacs` also has the same behavior. I think you should report the issue you mentioned above to upstream `vc-mode`. Or we find other ways to detect git info. `vc-mode` is nil in `dired` buffer.

BTW, I think it makes sense not displaying branch info for ignored files, otherwise you shouldn't add them to `.gitignore`.

**Comment by valignatev** [comment]
> BTW, I think it makes sense not displaying branch info for ignored files, otherwise you shouldn't add them to .gitignore, right?
It's debatable, I see this as a project info, no the individual file, but I see why it works like that, it makes sense as well.

Anyways, thanks for the links and your help, I think I'll handle that from here. :)
