### ISSUE TITLE
[Bug] battery status does not have percentage sign

### ISSUE THREAD

**Issue by Simon-Lin** [seagle0128/doom-modeline#606]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The battery section of the modeline displays the percentage but weirdly did not show the percentage sign.
![Screen Shot 2023-02-01 at 00 56 53](https://user-images.githubusercontent.com/7460398/215973117-e945a5b2-e9d4-4ee2-b8b1-feaa805d8632.png)

or with a clean Emacs setup:
![Screen Shot 2023-02-01 at 01 08 20](https://user-images.githubusercontent.com/7460398/215975031-51e45feb-6225-4ccf-99ec-920fec7d1bcc.png)

### Steps to reproduce

Load doom-modeline and evaluate `(display-battery-mode)`.

### Expected behavior

The battery percentage should be shown with a percentage sign, like 96%.

### OS

MacOS

### Emacs Version

28

### Anything else

In my minimal setup test, `(eval 'doom-modeline--battery-status)` gives

`(#("+" 0 1 (face doom-modeline-battery-charging help-echo "Power AC, battery high (100% load, remaining time 0:00)")) . #("100%%" 0 5 (help-echo "Power AC, battery high (100% load, remaining time 0:00)" face doom-modeline-battery-charging)))`

So there seems to be a percentage sign in the modeline string. But somehow it is not displayed.

**Comment by samrjack** [comment]
Hmm, I'm now seeing the opposite issue of having two percent signs show up. This is fixed by reverting the change made in d8f9ec7. Any idea what could be causing the discrepancy between the behavior shown above and the behavior I'm seeing?

<img width="218" alt="Screenshot 2023-02-27 at 12 09 40 PM" src="https://user-images.githubusercontent.com/17416498/221672509-e54ff8c4-b840-4c75-a744-684e5b2ad00f.png">

I don't have time to set up a minimal test env right now, but I can give it a try later if needed.

**Comment by seagle0128** [comment]
Hmm, it seems different behaviors for different versions.
