### ISSUE TITLE
[Bug] Doom modeline a bit slow under wayland(pgtk build)

### ISSUE THREAD

**Issue by jilen** [seagle0128/doom-modeline#665]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [x] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

![Screenshot from 2023-09-20 19-00-44](https://github.com/seagle0128/doom-modeline/assets/546573/a4888a85-b39a-4526-b016-c5b82050096f)

### Steps to reproduce

Build emacs with pgtk

### Expected behavior

Should as faster as default gtk build.

### OS

Linux

### Emacs Version

29 (gccemacs)

**Comment by jilen** [comment]
The profiler data produced by just move cursor randomly

**Comment by seagle0128** [comment]
So why do you think `doom-modeline` is slow? Its CPU usage is not very high.

**Comment by FlorianFranzen** [comment]
I had the exact same problem: With `doom-modeline` enabled, scrolling would freeze Emacs completely. I also noticed that none of the icons were displaying, so I changed `nerd-icons-font-family` to a different Nerd Font and the issue went away (incl. the icons coming back). Probably a combination of the way modeline uses icons and what happens if the icons can not be found.
